### ISSUE TITLE
退款证书参数是否可增加 []byte 类型

### ISSUE THREAD

**Issue by painkiller0513** [wleven/wxpay#10]
**应用场景**
对于 SaaS 系统来说，保存着多个商户的证书文件，通常文件不会保存到服务器上，而将其保存在 S3 或其它对象存储中。因此无法直接设置证书文件路径。

**优化建议**
是否可以优化下，为其增加新的证书字段，以让其支持设置证书内容，而非证书文件路径？

**Comment by helloh2o** [comment]
有的，用这个方法
func (w *Client) AddCertPemFileContent(certFileContent, keyFileContent []byte) (err error) {
	return w.addCertFileContentOrPath(certFileContent, keyFileContent, nil)
}

**Comment by wleven** [comment]
> 有的，用这个方法 func (w *Client) AddCertPemFileContent(certFileContent, keyFileContent []byte) (err error) { return w.addCertFileContentOrPath(certFileContent, keyFileContent, nil) }

没有这个方法吧😂

**Comment by helloh2o** [comment]
@wleven 那还不抓紧给大哥写一个。——>_<——

**Comment by wleven** [comment]
> @wleven 那还不抓紧给大哥写一个。——>_<——

在做了在做了🤣
