### ISSUE TITLE
求教：2018年后微信证书工具不提供rootca.pem了 那么到哪里可以找到呢？

### ISSUE THREAD

**Issue by shiniuyeyou** [wleven/wxpay#7]

**Comment by wleven** [comment]
用官方证书工具生成

**Comment by hzxgo** [comment]
@wleven 建议你修改下你的代码，若根证书未配置则发起Http请求时就不设置RootCAs。

**Comment by painkiller0513** [comment]
@wleven 我也遇到题主的问题，而且在 Google 上搜索「微信支付根证书」找不到相关文章，我使用的官方证书工具生成的证书有三个，分别是 apiclient_cert.p12、apiclient_cert.pem 和 apiclient_key.pem。没有根证书。
另外我查看微信支付有关退款接口的文档，也没有提到根证书的事情，根证书是不是个历史问题呢？
是不是现在已经不需要根证书了呢？

能帮忙解释清楚下吗？不尽感激！

**Comment by wleven** [comment]
由于绝大部分操作系统已内置了微信支付服务器证书的根CA证书, 2018年3月6日后, 不再提供CA证书文件（rootca.pem）下载。
这个证书应该是通用的，你可以百度下载一个rootca.pem试一下

**Comment by wleven** [comment]
由于绝大部分操作系统已内置了微信支付服务器证书的根CA证书, 2018年3月6日后, 不再提供CA证书文件（rootca.pem）下载。
这个证书应该是通用的，你可以百度下载一个rootca.pem试一下 @painkiller0513

**Comment by painkiller0513** [comment]
我从 CentOS 下找了一个根证书，可以使用，谢谢您！
